### ISSUE TITLE
orderservice

### ISSUE THREAD

**Issue by AniSkyWorker** [AlK2x/go_backend_course#2]
- [x] нет линтера
- [x] методы и структуры в handlers и logger - экспортируются наружу из пакета transport(пишутся с заглавной буквы), по сути экспортировать нужно только метод NewRouter 
- [x] можно добавить обработку отсутствия orderId, и возвращать badRequest

В остальном супер!

**Comment by AlK2x** [comment]
- [ ] Про отсутствие линтера непонятно. Код проверен, вызов линтера есть в makefile.
- [ ] Область видимости структур и методов исправлена
- [ ] Добавлена обарбока BadRequest

**Comment by AlK2x** [comment]
- [ ] Про линтер непонятно. Код проверен, вызов линтера есть в makefile.
- [ ] Область видимости испрвлена
- [ ] Добавлен ответ BadRequest
